export function ufArray() {
    return [
        { value: 1, name: 'AC' },
        { value: 2, name: 'AL' },
        { value: 3, name: 'AP' },
        { value: 4, name: 'AM' },
        { value: 5, name: 'BA' },
        { value: 6, name: 'CE' },
        { value: 7, name: 'DF' },
        { value: 8, name: 'ES' },
        { value: 9, name: 'GO' },
        { value: 10, name: 'MA' },
        { value: 11, name: 'MT' },
        { value: 12, name: 'MS' },
        { value: 13, name: 'MG' },
        { value: 14, name: 'PA' },
        { value: 15, name: 'PB' },
        { value: 16, name: 'PR' },
        { value: 17, name: 'PE' },
        { value: 18, name: 'PI' },
        { value: 19, name: 'RJ' },
        { value: 20, name: 'RN' },
        { value: 21, name: 'RS' },
        { value: 22, name: 'RO' },
        { value: 23, name: 'RR' },
        { value: 24, name: 'SC' },
        { value: 25, name: 'SP' },
        { value: 26, name: 'SE' },
        { value: 27, name: 'TO' }
    ]
}